# Machine Learning - Linear Algebra Review

**Matrice:** A 2D array

$$\begin{bmatrix}
a & b & c \\
d & e & f \\
j & k & l
\end{bmatrix}$$

A matrix with four rows and three columns ($4 \times 3$) matrix

**Vector:** Matrix with one column and many rows $\rightarrow$ subset of matrices

$$\begin{bmatrix}
w & x & y & z\\
\end{bmatrix}$$

This vector is a $4\times1$ matrix

## Notation and Terms

**Scalar** $\rightarrow$ Single value, not a vector or matrix

$A_{ij}$ $\rightarrow$ Element in the $i$th row and $j$th column of matrix $A$

$n$-dimensional vector $\rightarrow$ Vector with $n$ rows

$\mathbb{R}$ $\rightarrow$ Set of scalar real numbers

$\mathbb{R}^n$ $\rightarrow$ Set of n-dimensional vectors of real numbers 

Notes:
 - Matlab is 1-indexed, Python is 0-indexed
 - Matrices are usually uppercase while vectors are lowercase

## Vector Creation and Dimensions

In [13]:
import numpy as np

# Initialize a matrix
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

# Initialize a vector
v = np.array([[1],
              [2],
              [3]])

# Get the dimension of matrix A
dim_A = A.shape

# Get the dimension of the vector v
dim_v = v.shape

# Index into row 2 column 3 of matrix A
A_23 = A[1][2]

print("Matrix A")
print(A)
print("\nVector v")
print(v)
print("\nDimension of A = " + str(dim_A))
print("Dimension of v = " + str(dim_v))
print("\nValue at Row 2 Column 3 = " + str(A_23))

Matrix A
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector v
[[1]
 [2]
 [3]]

Dimension of A = (4, 3)
Dimension of v = (3, 1)

Value at Row 2 Column 3 = 6


## Addition and Subtraction

Matrix addition and subtraction is *element-wise* $\rightarrow$ add or subtract corresponding elements

$$\text{Addition: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} + 
\begin{bmatrix}
w & x \\
y & z
\end{bmatrix} =
\begin{bmatrix}
a+w & b+x \\
c+y & d+z
\end{bmatrix}$$

$$\text{Subtraction: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} - 
\begin{bmatrix}
w & x \\
y & z
\end{bmatrix} =
\begin{bmatrix}
a-w & b-x \\
c-y & d-z
\end{bmatrix}$$

Dimensionality must be the same for matrix addition and subtraction

In [20]:
# Initialize matrix A and B
A = np.array([[1,2,4],
              [5,3,2]])
B = np.array([[1,3,4],
              [1,1,1]])
# Initialize scalar s
s = 2

# Addition
add_AB = A+B
# Subtraction
sub_AB = A-B
# Scalar Addition
add_As = A+s

print("Matrix A")
print(A)
print("\nMatrix B")
print(B)
print("\nScalar s")
print(s)

print("\nAddition")
print(add_AB)
print("\nSubtraction")
print(sub_AB)
print("\nScalar Addition")
print(add_As)

Matrix A
[[1 2 4]
 [5 3 2]]

Matrix B
[[1 3 4]
 [1 1 1]]

Scalar s
2

Addition
[[2 5 8]
 [6 4 3]]

Subtraction
[[ 0 -1  0]
 [ 4  2  1]]

Scalar Addition
[[3 4 6]
 [7 5 4]]


## Scalar Multiplication and Division

With scalar multiplication/division, we multiply/divide each element by the scalar

$$\text{Multiplication: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} \cdot x = 
\begin{bmatrix}
ax & bx \\
cx & dx
\end{bmatrix}$$

$$\text{Division: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} \div x = 
\begin{bmatrix}
\frac{a}{x} & \frac{b}{x} \\
\frac{c}{x} & \frac{d}{x}
\end{bmatrix}$$



In [21]:
# Scalar Multiplication
mult_As = A*s
# Scalar Division
div_As = A/s

print("Scalar Multiplication")
print(mult_As)
print("\nScalar Division")
print(div_As)

Scalar Multiplication
[[ 2  4  8]
 [10  6  4]]

Scalar Division
[[0.5 1.  2. ]
 [2.5 1.5 1. ]]


## Matrix-Vector Multiplication and Division

Map the column of the vector to each row of the matrix, multiply each element, and sum the result
 - Matrix-vector multiplication results in a vector
 - Number of cols must equal number of rows
 - $m \times n$ matrix multiplied by $n \times 1$ vector results in $m \times 1$ vector
 
$$\begin{bmatrix}
a & b \\
c & d \\
e & f \\
\end{bmatrix} \cdot
\begin{bmatrix}
x \\
y
\end{bmatrix} =
\begin{bmatrix}
ax+by \\
cx+dy \\
ex+fy
\end{bmatrix}$$

In [29]:
# TODO TODO TODO
# # Initialize matrix A
# A = np.array([[1,2,3],
#               [4,5,6],
#               [7,8,9]])
# # Initialize vector v
# v = np.array([[2],
#               [1],
#               [1]])

# # Multiply A * v
# Av = A*v

# print("Matrix-Vector Multiplication")
# print(Av)