# Machine Learning - Linear Algebra Review

**Matrice:** A 2D array

$$\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i \\
j & k & l
\end{bmatrix}$$

A matrix with four rows and three columns ($4 \times 3$) matrix

**Vector:** Matrix with one column and many rows $\rightarrow$ subset of matrices

$$\begin{bmatrix}
w \\
x \\
y \\
z\end{bmatrix}$$

This vector is a $4\times1$ matrix

## Notation and Terms

**Scalar** $\rightarrow$ Single value, not a vector or matrix

$A_{ij}$ $\rightarrow$ Element in the $i$th row and $j$th column of matrix $A$

$v_i$ $\rightarrow$ Element in the $i$th row of vector $v$

$n$-dimensional vector $\rightarrow$ Vector with $n$ rows

$\mathbb{R}$ $\rightarrow$ Set of scalar real numbers

$\mathbb{R}^n$ $\rightarrow$ Set of n-dimensional vectors of real numbers 

Matrices are usually uppercase while vectors are lowercase

Notes on Matlab/Python Comparison:
 - Matlab is 1-indexed, Python is 0-indexed
 - Matlab vectors are by default $m \times 1$, whereas python vectors are by default $m$
     - To promote a Python vector to $m \times 1$ use `v[:,None]`
     - To promote a Python vector to $1 \times n$ use `v[None,:]`

## Vector Creation and Dimensions

In [1]:
import numpy as np

# Initialize a matrix
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])

# Initialize a vector
v = np.array([1,2,3])

# Get the dimension of matrix A
dim_A = A.shape

# Get the dimension of the vector v
dim_v = v.shape
# Promote v to a column matrix
dim_v_matrix = v[:,None].shape

# Index into row 2 column 3 of matrix A
A_23 = A[1][2]

print("Matrix A")
print(A)
print("\nVector v")
print(v)
print("Promoted to Matrix")
print(v[:,None])
print("\nDimension of A = " + str(dim_A))
print("Dimension of v = " + str(dim_v))
print("Dimension of v Promoted to Matrix = " + str(dim_v_matrix))
print("\nValue at Row 2 Column 3 = " + str(A_23))

Matrix A
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector v
[1 2 3]
Promoted to Matrix
[[1]
 [2]
 [3]]

Dimension of A = (4, 3)
Dimension of v = (3,)
Dimension of v Promoted to Matrix = (3, 1)

Value at Row 2 Column 3 = 6


## Addition and Subtraction

Matrix addition and subtraction is *element-wise* $\rightarrow$ add or subtract corresponding elements

$$\text{Addition: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} + 
\begin{bmatrix}
w & x \\
y & z
\end{bmatrix} =
\begin{bmatrix}
a+w & b+x \\
c+y & d+z
\end{bmatrix}$$

$$\text{Subtraction: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} - 
\begin{bmatrix}
w & x \\
y & z
\end{bmatrix} =
\begin{bmatrix}
a-w & b-x \\
c-y & d-z
\end{bmatrix}$$

Dimensionality must be the same for matrix addition and subtraction

In [2]:
# Initialize matrix A and B
A = np.array([[1,2,4],
              [5,3,2]])
B = np.array([[1,3,4],
              [1,1,1]])
# Initialize scalar s
s = 2

# Addition
add_AB = A+B
# Subtraction
sub_AB = A-B
# Scalar Addition
add_As = A+s

print("Matrix A")
print(A)
print("\nMatrix B")
print(B)
print("\nScalar s")
print(s)

print("\nAddition")
print(add_AB)
print("\nSubtraction")
print(sub_AB)
print("\nScalar Addition")
print(add_As)

Matrix A
[[1 2 4]
 [5 3 2]]

Matrix B
[[1 3 4]
 [1 1 1]]

Scalar s
2

Addition
[[2 5 8]
 [6 4 3]]

Subtraction
[[ 0 -1  0]
 [ 4  2  1]]

Scalar Addition
[[3 4 6]
 [7 5 4]]


## Scalar Multiplication and Division

With scalar multiplication/division, we multiply/divide each element by the scalar

$$\text{Multiplication: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} \cdot x = 
\begin{bmatrix}
ax & bx \\
cx & dx
\end{bmatrix}$$

$$\text{Division: }
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix} \div x = 
\begin{bmatrix}
\frac{a}{x} & \frac{b}{x} \\
\frac{c}{x} & \frac{d}{x}
\end{bmatrix}$$



In [3]:
# Scalar Multiplication
mult_As = A*s
# Scalar Division
div_As = A/s

print("Scalar Multiplication")
print(mult_As)
print("\nScalar Division")
print(div_As)

Scalar Multiplication
[[ 2  4  8]
 [10  6  4]]

Scalar Division
[[0.5 1.  2. ]
 [2.5 1.5 1. ]]


## Matrix-Vector Multiplication and Division

Map the column of the vector to each row of the matrix, multiply each element, and sum the result
 - Matrix-vector multiplication results in a vector
 - Number of cols must equal number of rows
 - $m \times n$ matrix multiplied by $n \times 1$ vector results in $m \times 1$ vector
 
$$\begin{bmatrix}
a & b \\
c & d \\
e & f \\
\end{bmatrix} \cdot
\begin{bmatrix}
x \\
y
\end{bmatrix} =
\begin{bmatrix}
ax+by \\
cx+dy \\
ex+fy
\end{bmatrix}$$

In [4]:
# Initialize matrix A
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
# Initialize vector v
v = np.array([1,1,1])

# Multiply A * v
# Note: np.dot (A,v) considers v nx1, np.dot(v,A) considers v 1xn
Av = np.dot(A,v)

print("Matrix-Vector Multiplication")
print(Av)

Matrix-Vector Multiplication
[ 6 15 24]


## Matrix-Matrix Multiplication

Multiply matrix A by matrix B by breaking B into component vectors and multiply A by each vector in B, concatenating the result
 - $m \times n$ matrix multiplied by $n \times o$ matrix results in an $m \times o$ matrix
 - Num cols in the first matrix must equal num rows in the second matrix

$$\begin{bmatrix}
a & b \\
c & d \\
e & f \\
\end{bmatrix} \cdot
\begin{bmatrix}
w & x \\
y & z
\end{bmatrix} =
\begin{bmatrix}
aw+by & ax+bz \\
cw+dy & cx+dz \\
ew+fy & ex+fz
\end{bmatrix}$$

In [5]:
# Initialize a 3x2 matrix A
A = np.array([[1,2],
              [3,4],
              [5,6]])

# Initialize a 2x1 matrix B
B = np.array([1,2])

# Multiply A*B: Expect a matrix of (3x2)*(2x1)=(3x1)
AB = np.dot(A,B)

print("Matrix-Matrix Multiplication")
print(AB)

Matrix-Matrix Multiplication
[ 5 11 17]


## Matrix Multiplication Properties

Matrices are not commutative: $A \cdot B \neq B \cdot A$

Matrices are associative: $(A \cdot B) \cdot C = A \cdot (B \cdot C)$

**Identity Matrix:** When multiplied by any matrix of the same dimension, it results in the original matrix
 - Has 1s on the diagonal (upper-left to lower-right diagonal), 0s elsewhere
 - When multiplying after some matrix ($A \times I$) the square identity matrix's dimension should match the other matrix's *columns*
 - When multiplying after some matrix ($I \times A$) the square identity matrix's dimension should match the other matrix's *rows*
 
$$\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 
\end{bmatrix}$$

In [6]:
# Initialize matrices A and B
A = np.array([[1,2],
              [4,5]])
B = np.array([[1,1],
              [0,2]])

# Initialize a 2x2 identity matrice
I = np.eye(2)

IA = np.dot(I,A)
AI = np.dot(A,I)

AB = np.dot(A,B)
BA = np.dot(B,A)

print("I*A = A*I")
print(IA)
print(AI)
print("\nA*B != B*A")
print(AB)
print(BA)

I*A = A*I
[[1. 2.]
 [4. 5.]]
[[1. 2.]
 [4. 5.]]

A*B != B*A
[[ 1  5]
 [ 4 14]]
[[ 5  7]
 [ 8 10]]


## Inverse and Transpose

**Inverse of Matrix:** Denoted by $A^{-1}$, multiplying by the inverse results in the identity matrix
 - Non-square matrices do not have an inverse matrix
 - *Singular/Degenerate* means the matrix doesn't have an inverse

**Transposition:** Rotating the matrix 90 degrees clockwise and then reversing it.

$$A = \begin{bmatrix}
a & b \\
c & d \\
e & f \\
\end{bmatrix} \rightarrow
A^T = \begin{bmatrix}
a & c & e \\
b & d & f
\end{bmatrix}
$$

Therefore, $A_{ij} = A_{ji}^T$

In [8]:
# Initialize matrix A
A = np.array([[1,2,0],
              [0,5,6],
              [7,0,9]])

# Transpose A
A_trans = A.transpose()

# Inverse of A
A_inv = np.linalg.pinv(A)

# Prove A^(-1)*A = Identity Matrix
I = np.dot(A_inv,A)

print(A_trans)
print(A_inv)
print(I)

[[1 0 7]
 [2 5 0]
 [0 6 9]]
[[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]
[[ 1.00000000e+00 -1.11022302e-16  7.91033905e-16]
 [ 2.77555756e-16  1.00000000e+00  1.11022302e-16]
 [-2.77555756e-16  0.00000000e+00  1.00000000e+00]]
